import type { CaptionStyle, StyleOverrides } from "./types";

export const CAPTION_STYLES: CaptionStyle[] = [
  {
    id: "classic",
    name: "Classic",
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSizeRatio: 0.045,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    mode: "plain",
    lineBackground: null,
    strokeRatio: 0.08,
    strokeColor: "#000000",
    shadow: "0 0.08em 0.25em rgba(0,0,0,0.75)",
    maxWordsPerPage: 6,
    animation: "none",
    positionY: 0.86,
  },
  {
    id: "hormozi",
    name: "Highlight",
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSizeRatio: 0.055,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#C8FF2E",
    mode: "highlight-color",
    lineBackground: null,
    strokeRatio: 0.1,
    strokeColor: "#000000",
    shadow: "0 0.1em 0.3em rgba(0,0,0,0.8)",
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.78,
  },
  {
    id: "wordbox",
    name: "Word Box",
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSizeRatio: 0.048,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#19C37D",
    mode: "highlight-box",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.08em 0.25em rgba(0,0,0,0.8)",
    maxWordsPerPage: 5,
    animation: "none",
    positionY: 0.84,
  },
  {
    id: "boxed",
    name: "Backdrop",
    fontFamily: "Oswald",
    fontWeight: 600,
    fontSizeRatio: 0.046,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#FFD43B",
    mode: "highlight-color",
    lineBackground: "rgba(0,0,0,0.72)",
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: null,
    maxWordsPerPage: 6,
    animation: "fade",
    positionY: 0.86,
  },
  {
    id: "oneword",
    name: "One Word",
    fontFamily: "Unbounded",
    fontWeight: 700,
    fontSizeRatio: 0.065,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    mode: "one-word",
    lineBackground: null,
    strokeRatio: 0.06,
    strokeColor: "#000000",
    shadow: "0 0.1em 0.35em rgba(0,0,0,0.85)",
    maxWordsPerPage: 1,
    animation: "pop",
    positionY: 0.5,
  },
  {
    id: "karaoke",
    name: "Karaoke",
    fontFamily: "Oswald",
    fontWeight: 600,
    fontSizeRatio: 0.052,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#4DA3FF",
    mode: "karaoke",
    lineBackground: null,
    strokeRatio: 0.07,
    strokeColor: "#0A0A0A",
    shadow: "0 0.08em 0.3em rgba(0,0,0,0.8)",
    maxWordsPerPage: 5,
    animation: "slide-up",
    positionY: 0.82,
  },
  {
    id: "beast",
    name: "Beast",
    fontFamily: "Unbounded",
    fontWeight: 900,
    fontSizeRatio: 0.052,
    uppercase: true,
    textColor: "#FFD600",
    highlightColor: "#FFFFFF",
    mode: "plain",
    lineBackground: null,
    strokeRatio: 0.12,
    strokeColor: "#000000",
    shadow: "0 0.1em 0 rgba(0,0,0,0.45)",
    maxWordsPerPage: 3,
    animation: "pop",
    positionY: 0.5,
    colorCycle: ["#FFD600", "#3BFF6E", "#FF4D4D", "#4DA3FF"],
    activeScale: 1.12,
  },
  {
    id: "neon",
    name: "Neon",
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSizeRatio: 0.05,
    uppercase: true,
    textColor: "#9BF6FF",
    highlightColor: "#FF2EC8",
    mode: "highlight-color",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow:
      "0 0 0.12em #00F0FF, 0 0 0.35em rgba(0,240,255,0.85), 0 0 0.9em rgba(0,240,255,0.5)",
    maxWordsPerPage: 4,
    animation: "fade",
    positionY: 0.8,
    letterSpacingEm: 0.04,
  },
  {
    id: "marker",
    name: "Marker",
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSizeRatio: 0.048,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#FFE600",
    mode: "highlight-box",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.08em 0.25em rgba(0,0,0,0.8)",
    maxWordsPerPage: 5,
    animation: "none",
    positionY: 0.84,
    boxRotate: -2,
  },
  {
    id: "gradient",
    name: "Gradient",
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSizeRatio: 0.054,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    mode: "plain",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: null,
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.78,
    gradient: "linear-gradient(180deg, #FFE53B 0%, #FF7A00 55%, #FF2525 100%)",
  },
  {
    id: "bubble",
    name: "Comic",
    fontFamily: "Unbounded",
    fontWeight: 700,
    fontSizeRatio: 0.046,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#FFD600",
    mode: "highlight-color",
    lineBackground: null,
    strokeRatio: 0.2,
    strokeColor: "#1A1A2E",
    shadow: "0.05em 0.09em 0 rgba(26,26,46,0.9)",
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.82,
  },
  {
    id: "retro3d",
    name: "Retro 3D",
    fontFamily: "Unbounded",
    fontWeight: 900,
    fontSizeRatio: 0.05,
    uppercase: true,
    textColor: "#FFF6E0",
    highlightColor: "#FFF6E0",
    mode: "plain",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0.045em 0.045em 0 #FF3B6B, 0.1em 0.1em 0 #2B2BD6",
    maxWordsPerPage: 3,
    animation: "slide-up",
    positionY: 0.5,
    letterSpacingEm: 0.02,
  },
  {
    id: "typewriter",
    name: "Typewriter",
    fontFamily: "JetBrainsMono",
    fontWeight: 700,
    fontSizeRatio: 0.038,
    uppercase: false,
    textColor: "#D7FF3F",
    highlightColor: "#FFFFFF",
    mode: "appear",
    lineBackground: "rgba(10,12,8,0.82)",
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: null,
    maxWordsPerPage: 7,
    animation: "none",
    positionY: 0.86,
  },
  {
    id: "opus",
    name: "Opus",
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSizeRatio: 0.05,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#7C3AED",
    mode: "highlight-box",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.08em 0.3em rgba(0,0,0,0.85)",
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.76,
  },
  {
    id: "minimal",
    name: "Minimal",
    fontFamily: "Montserrat",
    fontWeight: 500,
    fontSizeRatio: 0.034,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    mode: "karaoke",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.06em 0.4em rgba(0,0,0,0.9)",
    maxWordsPerPage: 7,
    animation: "fade",
    positionY: 0.88,
    letterSpacingEm: 0.06,
  },

  {
    id: "gold",
    name: "Gold",
    fontFamily: "PlayfairDisplay",
    fontWeight: 800,
    fontSizeRatio: 0.05,
    uppercase: true,
    textColor: "#F3D98A",
    highlightColor: "#FFFFFF",
    mode: "karaoke",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: null, // градиент — теней нельзя (bg-clip)
    maxWordsPerPage: 4,
    animation: "fade",
    positionY: 0.82,
    letterSpacingEm: 0.08,
    gradient: "linear-gradient(180deg, #FBEEC0 0%, #E8C15C 45%, #A5762B 100%)",
  },
  {
    id: "glitch",
    name: "Glitch",
    fontFamily: "Unbounded",
    fontWeight: 800,
    fontSizeRatio: 0.048,
    uppercase: true,
    textColor: "#EAFBFF",
    highlightColor: "#C8FF2E",
    mode: "highlight-color",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow:
      "-0.045em 0 0 rgba(255,46,200,0.9), 0.045em 0 0 rgba(0,229,255,0.9), 0 0.1em 0.35em rgba(0,0,0,0.7)",
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.8,
    letterSpacingEm: 0.05,
  },
  {
    id: "sticker",
    name: "Sticker",
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSizeRatio: 0.05,
    uppercase: true,
    textColor: "#FF6B9D",
    highlightColor: "#FFFFFF",
    mode: "plain",
    lineBackground: null,
    strokeRatio: 0.14,
    strokeColor: "#FFFFFF",
    shadow: "0 0.09em 0.22em rgba(0,0,0,0.55)",
    maxWordsPerPage: 3,
    animation: "pop",
    positionY: 0.8,
    colorCycle: ["#FF6B9D", "#4DD4FF", "#FFD93D", "#7CFF6B"],
    activeScale: 1.12,
  },

  // ─── журнальные design-пресеты: слова в столбик, микс шрифтов и размеров ───
  {
    id: "vogue",
    name: "Cover",
    fontFamily: "PlayfairDisplay",
    fontWeight: 700,
    fontSizeRatio: 0.088,
    uppercase: false,
    textColor: "#FFF8EE",
    highlightColor: "#FFF8EE",
    mode: "design",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.06em 0.35em rgba(0,0,0,0.75)",
    maxWordsPerPage: 4,
    animation: "fade",
    positionY: 0.5,
    designWords: [
      { sizeMult: 2.0, font: "PlayfairDisplay", weight: 900, caps: true, anim: "tracking" },
      { sizeMult: 0.8, font: "Montserrat", weight: 600, caps: true, ls: 0.3, anim: "blur" },
      { sizeMult: 1.5, font: "PlayfairDisplay", italic: true, color: "#E8C9A0", anim: "rise" },
      { sizeMult: 0.95, font: "Montserrat", weight: 700, caps: true, ls: 0.18, anim: "tracking" },
    ],
  },
  {
    id: "zine",
    name: "Zine",
    fontFamily: "Unbounded",
    fontWeight: 900,
    fontSizeRatio: 0.082,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#C8FF2E",
    mode: "design",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0.05em 0.07em 0 rgba(0,0,0,0.85)",
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.5,
    designWords: [
      { sizeMult: 1.8, caps: true, rotate: -3, color: "#C8FF2E", anim: "stamp" },
      { sizeMult: 1.0, font: "Oswald", weight: 700, caps: true, rotate: 1.5, bg: "#0A0B0D", anim: "slide-left" },
      { sizeMult: 1.4, caps: true, rotate: 2, anim: "whip" },
      { sizeMult: 0.85, font: "JetBrainsMono", weight: 800, rotate: -1, color: "#FF4D4D", anim: "slide-right" },
    ],
  },
  {
    id: "journal",
    name: "Editorial",
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSizeRatio: 0.084,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#FF3B30",
    mode: "design",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.07em 0.4em rgba(0,0,0,0.8)",
    maxWordsPerPage: 4,
    animation: "fade",
    positionY: 0.5,
    designWords: [
      { sizeMult: 0.95, font: "Oswald", weight: 600, caps: true, ls: 0.14, anim: "tracking" },
      { sizeMult: 2.0, font: "PlayfairDisplay", weight: 900, italic: true, color: "#FF3B30", anim: "blur" },
      { sizeMult: 1.2, font: "Montserrat", weight: 800, caps: true, anim: "slide-left" },
      { sizeMult: 1.55, font: "PlayfairDisplay", weight: 700, anim: "rise" },
    ],
  },
  {
    id: "sketch",
    name: "Sketch",
    fontFamily: "Caveat",
    fontWeight: 700,
    fontSizeRatio: 0.09,
    uppercase: false,
    textColor: "#FFFFFF",
    highlightColor: "#C8FF2E",
    mode: "design",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: "0 0.06em 0.3em rgba(0,0,0,0.8)",
    maxWordsPerPage: 4,
    animation: "pop",
    positionY: 0.5,
    designWords: [
      { sizeMult: 2.2, font: "Caveat", weight: 700, color: "#C8FF2E", rotate: -2, anim: "pop" },
      { sizeMult: 0.75, font: "JetBrainsMono", weight: 700, caps: true, anim: "flip" },
      { sizeMult: 1.7, font: "Caveat", weight: 700, rotate: 1.5, anim: "whip" },
      { sizeMult: 0.95, font: "Montserrat", weight: 800, caps: true, ls: 0.12, anim: "stamp" },
    ],
  },
  {
    id: "poster",
    name: "Poster",
    fontFamily: "Oswald",
    fontWeight: 700,
    fontSizeRatio: 0.084,
    uppercase: true,
    textColor: "#FFFFFF",
    highlightColor: "#C8FF2E",
    mode: "design",
    lineBackground: null,
    strokeRatio: 0,
    strokeColor: "#000000",
    shadow: null,
    maxWordsPerPage: 4,
    animation: "slide-up",
    positionY: 0.5,
    designWords: [
      { sizeMult: 1.65, caps: true, bg: "#0A0B0D", color: "#FFFFFF", anim: "flip" },
      { sizeMult: 1.0, caps: true, bg: "#C8FF2E", color: "#0A0B0D", anim: "stamp" },
      { sizeMult: 1.3, caps: true, bg: "#0A0B0D", color: "#FFFFFF", anim: "slide-left" },
      { sizeMult: 0.8, caps: true, bg: "#FF3B30", color: "#FFFFFF", anim: "rise" },
    ],
  },
];

export function getStyle(styleId: string): CaptionStyle {
  return CAPTION_STYLES.find((s) => s.id === styleId) ?? CAPTION_STYLES[0];
}

export function resolveStyle(
  styleId: string,
  overrides: StyleOverrides
): CaptionStyle {
  const base = getStyle(styleId);
  const merged = { ...base, ...stripUndefined(overrides) };
  if (merged.mode === "one-word") merged.maxWordsPerPage = 1;
  return merged;
}

/** Отбирает из произвольного JSON только допустимые поля StyleOverrides. */
export function sanitizeOverrides(input: unknown): StyleOverrides {
  if (!input || typeof input !== "object") return {};
  const src = input as Record<string, unknown>;
  const out: StyleOverrides = {};
  if (typeof src.fontFamily === "string" && src.fontFamily.trim()) {
    out.fontFamily = src.fontFamily.trim();
  }
  if (typeof src.fontSizeRatio === "number" && Number.isFinite(src.fontSizeRatio)) {
    out.fontSizeRatio = Math.min(Math.max(src.fontSizeRatio, 0.01), 0.2);
  }
  if (typeof src.uppercase === "boolean") out.uppercase = src.uppercase;
  if (typeof src.textColor === "string") out.textColor = src.textColor;
  if (typeof src.highlightColor === "string") out.highlightColor = src.highlightColor;
  if (typeof src.maxWordsPerPage === "number" && Number.isFinite(src.maxWordsPerPage)) {
    out.maxWordsPerPage = Math.min(Math.max(Math.round(src.maxWordsPerPage), 1), 12);
  }
  if (typeof src.positionY === "number" && Number.isFinite(src.positionY)) {
    out.positionY = Math.min(Math.max(src.positionY, 0), 1);
  }
  return out;
}

function stripUndefined<T extends object>(obj: T): T {
  const out = {} as T;
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined && v !== null) (out as Record<string, unknown>)[k] = v;
  }
  return out;
}
